version: '3.9'

services:
  web:
    build: .
    container_name: zap_web
    ports:
      - "5000:5000"
    environment:
      - ZAP_API_KEY=${ZAP_API_KEY}
      - ZAP_URL=http://zap:8090
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - REPORT_DIR=/app/reportes
      - APP_USERNAME=${APP_USERNAME}
      - APP_PASSWORD=${APP_PASSWORD}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - PSQL_HOST=db
      - PSQL_PORT=5432
      - PSQL_USER=${PSQL_USER}
      - PSQL_PASSWORD=${PSQL_PASSWORD}
    depends_on:
      - db
      - zap
    volumes:
      - ./reportes:/app/reportes

  db:
    image: postgres:13
    container_name: zap_postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: zap_data_base
    volumes:
      - pgdata:/var/lib/postgresql/data

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap_container
    ports:
      - "8090:8090"
    command: >
      zap.sh -daemon -host 0.0.0.0 -port 8090
      -config api.disablekey=false
      -config api.key=${ZAP_API_KEY}
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
    volumes:
      - ./reportes:/app/reportes

volumes:
  pgdata:
