version: "3.9"

services:
  db:
    image: postgres:17.4
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zap:
    image: owasp/zap2docker-stable
    container_name: zap
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    ports:
      - "8080:8080"
    restart: always

  app:
    build: .
    container_name: flask_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - zap
    ports:
      - "5000:5000"
    environment:
      - PSQL_HOST=db
      - PSQL_PORT=5432
      - PSQL_USER=${PSQL_USER}
      - PSQL_PASSWORD=${PSQL_PASSWORD}
      - PSQL_DB=${PSQL_DB}
      - ZAP_API_KEY=${ZAP_API_KEY}
      - ZAP_URL=${ZAP_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - REPORT_DIR=${REPORT_DIR}
      - APP_USERNAME=${APP_USERNAME}
      - APP_PASSWORD=${APP_PASSWORD}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    volumes:
      - ./reports:/reports

volumes:
  pgdata:
